project:
  type: website
  output-dir: _site

website:
  title: "AEM 6850"
  description: "AEM 6850 course site — Cornell Dyson School, Prof. Ariel Ortiz-Bobea."
  navbar:
    background: dark
    title: "AEM 6850"
    right:
      - text: "Home"
        href: index.qmd

format:
  html:
    theme: cosmo
    toc: false
    css: styles.css
    page-layout: full
